# Generated by Django 5.1.5 on 2025-02-03 10:23

import core.extras.tools
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "public_key",
                    models.UUIDField(
                        db_index=True,
                        default=core.extras.tools.generate_uuid,
                        unique=True,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("limit", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "public_key",
                    models.UUIDField(
                        db_index=True,
                        default=core.extras.tools.generate_uuid,
                        unique=True,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=50)),
                ("birth_date", models.DateField()),
                (
                    "Agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="childrens",
                        to="agent.agent",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="child.level"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
