# Generated by Django 5.1.5 on 2025-02-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="index",
            field=models.IntegerField(null=True),
        ),
    ]
