# Generated by Django 5.1.5 on 2025-02-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_agent_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="children",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="family_aid",
            field=models.IntegerField(null=True),
        ),
    ]
