# Generated by Django 5.1.5 on 2025-02-03 10:23

import core.extras.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "public_key",
                    models.UUIDField(
                        db_index=True,
                        default=core.extras.tools.generate_uuid,
                        unique=True,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("index", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
