# Generated by Django 5.1.5 on 2025-02-03 10:23

import core.extras.tools
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "public_key",
                    models.UUIDField(
                        db_index=True,
                        default=core.extras.tools.generate_uuid,
                        unique=True,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentPayElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "public_key",
                    models.UUIDField(
                        db_index=True,
                        default=core.extras.tools.generate_uuid,
                        unique=True,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField()),
                ("start_at", models.DateField()),
                ("end_at", models.DateField(null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agent.agent"
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pay.payelement"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "public_key",
                    models.UUIDField(
                        db_index=True,
                        default=core.extras.tools.generate_uuid,
                        unique=True,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_amount", models.IntegerField()),
                ("retained_amount", models.IntegerField()),
                ("paied_amount", models.IntegerField()),
                ("dead_month", models.DateField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agent.agent"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElementDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "public_key",
                    models.UUIDField(
                        db_index=True,
                        default=core.extras.tools.generate_uuid,
                        unique=True,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pay.agentpayelement",
                    ),
                ),
                (
                    "monthly_pay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pay.monthlypay"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
